name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 새로운 기능이 추가되었어요'
    label: 
      - '🚀 feature'
      - 'feature'
      - 'enhancement'
      - 'implement'
      - 'update'
  - title: '🔨 자잘한 버그를 수정했어요'
    label: 
      - '🔨 fix'
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: '🐬 코드를 개선했어요'
    label:
      - '📋 docs'
      - 'docs'
      - '🧼 refactor'
      - 'refactor'
      - '🪄 setting'
      - 'setting'
      - '🎫 test'
      - 'test'
      - '🚀 deploy'
      - 'deploy'
change-template: '- $TITLE #$NUMBER @$AUTHOR '
template: |
  ## What's Changed
  ---
  $CHANGES
no-changes-template: '변경사항이 없어요'
version-resolver:
  major:
    labels:
      - '✨ major'
  minor:
    labels:
      - '🪄 minor'
  patch:
    labels:
      - '- '🧩 patch'
  default: patch